const numberTest = 10

numberTest = 10
try{
    numberTest = 10
}
catch(err){
    console.log(`Erro: ${err}`)
}